// <auto-generated />
using System;
using EmployeeTodoList.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeTodoList.Data.Migrations
{
    [DbContext(typeof(EmployeeTodoListContext))]
    [Migration("20200520130124_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeTodoList.Data.Domains.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeTodoList.Data.Domains.ToDoTask", b =>
                {
                    b.Property<int>("ToDoTaskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("EmployeeId");

                    b.Property<double>("Estimate");

                    b.Property<int>("PriorityLevel");

                    b.Property<int>("State");

                    b.Property<string>("Title");

                    b.HasKey("ToDoTaskId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ToDoTasks");
                });

            modelBuilder.Entity("EmployeeTodoList.Data.Domains.ToDoTask", b =>
                {
                    b.HasOne("EmployeeTodoList.Data.Domains.Employee", "Employee")
                        .WithMany("ToDoTasks")
                        .HasForeignKey("EmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
